In [6]:
!pip install control
!pip install matplotlib

In [1]:
import control as clt
import numpy as np
import matplotlib.pyplot as plt

In [10]:
# Define pendulum constants
m = 0.2 # mass of pendulum
M = 0.5 # mass of cart
l = 0.3 # length of pendulum 
I = m*pow((2*l),2)/12 # Moment of inertia (COM) [m*(2l)ˆ2]/12
J = I + m*l*l # 0.006 + 0.2*0.3*0.3 Icom + mlˆ2 (Parallel axis theorm)
g = 9.8
print(I, J)

0.005999999999999999 0.023999999999999997


In [15]:
# dx/dt = Ax + Bu
"""
    (M+m)x'' + mL*Cos(phi).phi'' = u + ML*Sin(phi).(phi')ˆ2        
    mL*Cos(phi)x'' + (I+mlˆ2)*phi'' = mgLSin(phi)

    We calculate [x'' phi'']
"""
D = (M+m)*J - (m*m*l*l)
A = np.array([
    [0, 1, 0, 0],
    [0, 0, (m*m*g*l*l)/D, 0],
    [0, 0, 0, 1],
    [0, 0, (M+m)*m*g*l/D, 0]
])

B = np.array([
    [0],
    [(J)/D],
    [0],
    [m*l/D]
])

Q = np.diag([1, 1, 40, 1])
R = np.array([[0.1]])  # control effort penalty
# print(A)
# print(B)

K, S, E = clt.lqr(A, B, Q, R)
print(K, S, E)

[[-3.16227766 -5.69124558 41.55409243  7.69196126]] [[ 1.79972987  1.11951381 -2.43241172 -0.51737563]
 [ 1.11951381  1.76661717 -3.86030842 -0.83185427]
 [-2.43241172 -3.86030842 18.53438962  2.4583134 ]
 [-0.51737563 -0.83185427  2.4583134   0.50196486]] [-16.14167878+0.j          -6.28071827+0.j
  -1.09667199+0.43216711j  -1.09667199-0.43216711j]
